environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
install:
  - "%PYTHON%\\python.exe -m pip install opencv-python pillow mock"
  - "%PYTHON%\\python.exe -m pip install codecov coverage nose"
build: off
test_script:
  - "%PYTHON%\\python.exe -m nose --with-coverage"
after_test:
  - "%PYTHON%\\Scripts\\coverage.exe run "
  - "%PYTHON%\\Scripts\\codecov.exe"
